#!/usr/bin/perl -w

use strict;
use warnings;

eval 'use Carp::Always'; # Not everyone has it

use Getopt::Long;
use File::Slurp;
use Encode qw(decode_utf8);
use Text::Markdown ();
use Template ();
use Template::Constants qw( :debug :chomp );

my $sourcepath = 's';
my $buildpath  = 'build';

GetOptions(
    'sourcepath:s' => \$sourcepath,
    'buildpath:s'  => \$buildpath,
) or exit;

-d $buildpath && -w $buildpath or die;

my @pages = qw(
    index.html
);

MAIN: {
    my $m = Text::Markdown->new;

    my @sidelinks;

    my %tt_defaults = (
        INCLUDE_PATH => [ qw( tt ) ],
        OUTPUT_PATH  => $buildpath,
        DEBUG        => DEBUG_UNDEF,
        TRIM         => CHOMP_ALL,
        PRE_CHOMP    => 1,
        POST_CHOMP   => 1,
        ENCODING     => 'utf8',
    );

    my $tt = Template->new( \%tt_defaults );

    for my $target ( @pages ) {
        my $source = $target;
        $source =~ s/\.html$/.ttml/ or die;

        my $vars = {};
        $tt->process( $source, $vars, $target, { binmode => ':encoding(UTF-8)' } )
            or die sprintf( "file: %s\nerror: %s\n", $target, $tt->error );
    }
}
