#!/usr/bin/perl -w

use strict;
use warnings;

eval 'use Carp::Always'; # Not everyone has it

use Getopt::Long;
use Template ();
use Template::Constants qw( :debug :chomp );

exit main();

sub main {
    my $sourcepath = 's';
    my $buildpath  = 'build';

    GetOptions(
        'sourcepath:s' => \$sourcepath,
        'buildpath:s'  => \$buildpath,
    ) or exit;

    -d $buildpath && -w $buildpath or die;

    # XXX This should not be hardcoded
    my @pages = qw(
    index.html
    installation.html
    community.html
    others.html
    testimonials.html
    why-ack.html
    );

    MAIN: {
        my %tt_settings = (
            INCLUDE_PATH => [ qw( tt tt/wrapper ) ],
            OUTPUT_PATH  => $buildpath,
            DEBUG        => DEBUG_UNDEF,
            TRIM         => CHOMP_ALL,
            PRE_CHOMP    => 1,
            POST_CHOMP   => 1,
            ENCODING     => 'utf8',
        );

        my $tt = Template->new( \%tt_settings );

        for my $target ( @pages ) {
            my $source = $target;
            $source =~ s/\.html$/.ttml/ or die;

            my $vars = {};
            $tt->process( $source, $vars, $target, { binmode => ':encoding(UTF-8)' } )
                or die sprintf( "file: %s\nerror: %s\n", $target, $tt->error );
        }
    }

    return 0;
}
